#!/bin/env bash

if [ "$1" = "" ]; then
  echo "Usage: $0 <Network_Name>"
  exit 1
fi

MSG=$(nmcli connection show "$1" 2>&1)
RT_CODE=$?

if [ $RT_CODE -gt 0 ]; then
  echo $MSG
  exit $RT_CODE
fi

nmcli connection show "$1" -s | grep psk: | awk '{print $2}'
exit $?

